#!/usr/bin/env bash

set -euo pipefail

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

URL=https://releases.hashicorp.com/terraform/0.9.5/terraform_0.9.5_darwin_amd64.zip
ZIPFILE=${URL##*/}

cd $BASE
if ! [ -x terraform ];then
	echo "Downloading terraform"
	curl -O $URL
        unzip ${URL##*/}
	rm  -f $ZIPFILE
fi

exec $BASE/terraform
