#!/usr/bin/env bash

set -euo pipefail

BASE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

case $(uname) in
    Darwin) osfamily=darwin ;;
    Linux) osfamily=darwin ;;
    *) echo "Unsupported system" >&2; exit 1 ;;
esac

URL=https://releases.hashicorp.com/terraform/0.9.5/terraform_0.9.5_${osfamily}_amd64.zip
ZIPFILE=${URL##*/}

if ! [ -x $BASE/terraform ];then
	echo "Downloading terraform"
	curl -O$BASE/terraform $URL
    unzip ${URL##*/}
	rm  -f $ZIPFILE
fi

exec $BASE/terraform $@
