version: '2.1'

services:
  jenkins:
    #image: 'cloudowski/jenkins:1.1'
    build: ./image/
    hostname: 'jenkins.localhost'
    ports:
      - '8888:8080'
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
